" DROP TABLE IF EXISTS my_extra_table;"
" \p\g"
" "
" CREATE TABLE my_extra_table AS"
" SELECT "
"     cbr.rj_box_cid, cbr.retrieval_cid, cbr.section chunk, cbr.status cbr_status, cbr.box_id,"
"     lcr.position dest_pos, lcr.slot_number lcr_slot, lcr.process_cid lcr_procid, lcr.status lcr_status,"
"     lcr.cryovial_barcode, lcr.aliquot_type_cid"
" FROM "
"     c_box_retrieval cbr, l_cryovial_retrieval lcr"
" WHERE "
"     cbr.retrieval_cid=-1015"
" AND"
"     lcr.rj_box_cid=cbr.rj_box_cid;"
" \p\g"
" "
" COMMIT; "
" \p\g"
" "
" SELECT"
"     s1.retrieval_cid, g.chunk, g.rj_box_cid, g.cbr_status, g.dest_pos, g.lcr_slot, g.lcr_procid, g.lcr_status,"
"     s1.cryovial_id, s1.note_exists, s1.retrieval_cid, s1.box_cid, s1.status, s1.tube_position,"
"     s1.record_id, c.cryovial_barcode, c.sample_id, c.aliquot_type_cid, c.note_exists AS cryovial_note,"
"     s1.box_cid, b1.external_name AS src_box, s1.status, s1.tube_position, s1.note_exists AS cs_note,"
"     g.box_id AS dest_id, b2.external_name AS dest_name, s2.tube_position AS slot_number, s2.status AS dest_status"
" FROM"
"     my_extra_table g, cryovial c, cryovial_store s1, cryovial_store s2, box_name b1, box_name b2"
" WHERE "
"     c.cryovial_barcode = g.cryovial_barcode"
"     AND c.aliquot_type_cid = g.aliquot_type_cid"
"     AND s1.cryovial_id = c.cryovial_id"
"     AND s1.retrieval_cid = g.retrieval_cid"
"     AND b2.box_cid = g.box_id     "
"     AND b1.box_cid = s1.box_cid     "
"     AND s2.cryovial_id =c.cryovial_id"
"     AND b2.box_cid = s2.box_cid"
" ORDER BY "
"     s1.retrieval_cid,chunk, g.rj_box_cid, dest_pos;"
" \p\g"
"     "
" DROP my_extra_table;"
" \p\g"
" "
" COMMIT; "
" \p\g"